version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: credit-ijambo-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    restart: unless-stopped